name: Edit teammate finding comment
on: pull_request
jobs:
    delete-teammate-search-comments:
        runs-on: ubuntu-latest
        steps:
            - uses: corentinguilloteau/kth-devops-teammate@v2
              with:
                  issue: 1
                  pr_id: ${{ github.event.pull_request.number }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
